In [84]:
import gudhi
from methods import *
import random
import matplotlib.pyplot as plt

# 0 - Choose the protein structure you want to study

In [85]:
structure_id = "guanine"  #The code can be different if it is a molecule or a protein
file_name = "DATA//" + structure_id + ".pdb"

### 1 - Read the .pdb file and plot the 3D structure

In [86]:
structure = PDB_mol_reader(structure_id, file_name)
#structure = PDB_prot_reader(structure_id, file_name)
plot_3d(structure_id, structure)
print("Total number of carbon atoms: ", np.shape(structure[1])[0])

c:\Users\hosca\anaconda3\envs\project\lib\site-packages\Bio\PDB\PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 18
  warnings.warn(


Total number of carbon atoms:  16


### 2 - Analyse the 3D structure to determine the different values of epsilon

In [87]:
min = [np.min(idx) for idx in zip(*structure[1])]
max = [np.max(idx) for idx in zip(*structure[1])]

random_pair = [[random.randint(0, np.shape(structure[1])[0]-1), random.randint(0, np.shape(structure[1])[0]-1)]  for i in range(100)]
dist = np.sort(np.array([np.linalg.norm(structure[1][idx[0]] - structure[1][idx[1]]) for idx in random_pair]))

while dist[0] == 0:
    dist = dist[1:]

min_dist, max_dist = np.min(dist), np.max(dist)

epsilon = np.linspace(min_dist, max_dist, 3)

print(" Min (x,y,z): ", min,'\n',
    "Max (x,y,z): ", max, '\n',
    "Min euclidean distance: ", min_dist, '\n',
    "Max euclidean distance: ", max_dist, '\n',
    "Epsilon range: ", epsilon)

 Min (x,y,z):  [2.0, -1.81, 0.0] 
 Max (x,y,z):  [7.285, 1.81, 0.0] 
 Min euclidean distance:  0.99395186 
 Max euclidean distance:  5.0167623 
 Epsilon range:  [0.99395186 3.00535706 5.01676226]


In [88]:
rips_complex = []
simplex_tree = []
fmt = '%s -> %.2f'
fig = plt.figure(figsize=(14, 30))
subplot = [311, 312, 313]

for i in range(3):
    rips_complex.append(gudhi.RipsComplex(points = structure[1], max_edge_length = epsilon[i]))
    simplex_tree.append(rips_complex[i].create_simplex_tree(max_dimension=2))

    print('Rips complex is of dimension '  + \
        repr(simplex_tree[i].dimension()) + ' - ' + \
        repr(simplex_tree[i].num_simplices()) + ' simplices - ' + \
        repr(simplex_tree[i].num_vertices()) + ' vertices.') 

    res = ""
    for filtered_value in simplex_tree[0].get_filtration():
        res += fmt % tuple(filtered_value)
    #print(res)

    triangles = np.array([s[0] for s in simplex_tree[i].get_skeleton(2) if len(s[0])==3])

    ax = fig.add_subplot(subplot[i], projection='3d')
    ax.set_title("Vietoris Rips complex with epsilon of " + str(round(epsilon[i], 2)))
    ax.scatter(structure[1][:, 0], structure[1][:, 1], structure[1][:, 2], s=1)
    if len(triangles) != 0:
        ax.plot_trisurf(structure[1][:, 0], structure[1][:, 1], structure[1][:, 2], triangles=triangles, alpha = 0.1)

    plot = pv.Plotter(off_screen=True)
    plot.add_mesh(structure[1], color = 'k', render_points_as_spheres=True, point_size=2, show_scalar_bar=True)
    for triangle in triangles:
        x, y ,z = np.meshgrid([structure[1][triangle[0]][0], structure[1][triangle[1]][1], structure[1][triangle[2]][2]])
        grid = pv.StructuredGrid(x, y ,z)
        plot.add_mesh(grid, show_edges=True)
    plot.background_color = 'w'
    path = plot.generate_orbital_path(n_points=100, shift = 100, factor=3.0)
    plot.open_gif("RESULTS//Rips_" + str(round(epsilon[i], 2)) + "_" + structure_id + ".gif")
    plot.orbit_on_path(path, write_frames=True)
    plt.close() """

plt.show()

Rips complex is of dimension 1 - 23 simplices - 16 vertices.
Rips complex is of dimension 2 - 300 simplices - 16 vertices.


TypeError: points[0] must be a length three iterable of floats.

In [94]:
for triangle in triangles:
        print(triangle)
        print(structure[1][triangle[0]][0], structure[1][triangle[1]][1], structure[1][triangle[2]][2])

[0 1 2]
4.269 0.615 0.0
[0 1 3]
4.269 0.615 0.0
[0 1 6]
4.269 0.615 0.0
[0 1 7]
4.269 0.615 0.0
[0 1 8]
4.269 0.615 0.0
[0 1 9]
4.269 0.615 0.0
[ 0  1 11]
4.269 0.615 0.0
[0 2 3]
4.269 0.31 0.0
[0 2 6]
4.269 0.31 0.0
[0 2 7]
4.269 0.31 0.0
[0 2 8]
4.269 0.31 0.0
[0 2 9]
4.269 0.31 0.0
[ 0  2 12]
4.269 0.31 0.0
[0 3 6]
4.269 -1.19 0.0
[0 3 7]
4.269 -1.19 0.0
[0 3 8]
4.269 -1.19 0.0
[0 3 9]
4.269 -1.19 0.0
[ 0  3 12]
4.269 -1.19 0.0
[0 6 7]
4.269 0.31 0.0
[0 6 8]
4.269 0.31 0.0
[0 6 9]
4.269 0.31 0.0
[ 0  6 11]
4.269 0.31 0.0
[ 0  6 12]
4.269 0.31 0.0
[0 7 8]
4.269 -0.69 0.0
[0 7 9]
4.269 -0.69 0.0
[ 0  7 11]
4.269 -0.69 0.0
[ 0  7 12]
4.269 -0.69 0.0
[0 8 9]
4.269 0.81 0.0
[ 0  8 11]
4.269 0.81 0.0
[ 0  8 12]
4.269 0.81 0.0
[ 0  9 12]
4.269 -0.69 0.0
[1 2 3]
6.081 0.31 0.0
[1 2 4]
6.081 0.31 0.0
[1 2 6]
6.081 0.31 0.0
[1 2 7]
6.081 0.31 0.0
[1 2 8]
6.081 0.31 0.0
[1 2 9]
6.081 0.31 0.0
[1 3 4]
6.081 -1.19 0.0
[1 3 6]
6.081 -1.19 0.0
[1 3 7]
6.081 -1.19 0.0
[1 3 8]
6.081 -1.19 0.0
[1 3 9